source "https://rubygems.org"

gemspec

gem "capybara"
gem "debug"
gem "mocha"
gem "puma"
gem "redis"
gem "redis-namespace"
gem "resque"
gem "resque-pause"
gem "rubocop"
gem "rubocop-37signals"
gem "rubocop-performance"
gem "rubocop-rails"
gem "selenium-webdriver"
gem "solid_queue"
gem "sprockets-rails"
gem "sqlite3"
